// login
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_RESET = 'LOGIN_RESET';

// register
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_RESET = 'REGISTER_RESET';

// register
export const GET_CASES_ERROR = 'GET_CASES_ERROR';
export const GET_CASES_LOADING = 'GET_CASES_LOADING';
export const GET_CASES_SUCCESS = 'GET_CASES_SUCCESS';
export const GET_CASES_RESET = 'GET_CASES_RESET';
